-- Generated by scripts/generate-exit-survey-mapping-sql.ts
-- Source spreadsheet: Copy of mapping r.xlsx
BEGIN;
-- Ensure role column exists to hold organizational (non-permission) role.
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS role text;
-- Upsert departments for this company.
INSERT INTO public.departments (company_id, name)
VALUES
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Admissions'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Case Management'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Clinical'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Clinical + Medical'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Culinary'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Medical Director'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Nursing'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Pastoral Care'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Patient Advocacy'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Patient Experience'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Security'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Spa/Salon'),
  ('9ea3677d-be6c-46df-a41c-d22f01e88756', 'Tech Services')
ON CONFLICT (company_id, name) DO NOTHING;
-- Upsert employees from owner/member mapping.
UPDATE public.employees
SET full_name = 'Caitlyn Morgan',
    title = NULL,
    role = NULL,
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'cmorgan@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'cmorgan@honeylakeclinic.com', 'Caitlyn Morgan', NULL, NULL, 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'cmorgan@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Nikki George',
    title = NULL,
    role = 'Director of Admissions',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'ngeorge@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'ngeorge@honeylakeclinic.com', 'Nikki George', NULL, 'Director of Admissions', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'ngeorge@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Shaquel Payne',
    title = NULL,
    role = 'Director of Patient Experience',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'spayne@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'spayne@honeylakeclinic.com', 'Shaquel Payne', NULL, 'Director of Patient Experience', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'spayne@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Heather Plain',
    title = NULL,
    role = 'Facility Administrator',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'hplain@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'hplain@honeylakeclinic.com', 'Heather Plain', NULL, 'Facility Administrator', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'hplain@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Dawn Rettig',
    title = NULL,
    role = 'Wellness Director',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'drettig@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'drettig@honeylakeclinic.com', 'Dawn Rettig', NULL, 'Wellness Director', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'drettig@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Karl Benzio',
    title = 'Dr',
    role = 'Medical Director',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'kbenzio@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'kbenzio@honeylakeclinic.com', 'Karl Benzio', 'Dr', 'Medical Director', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'kbenzio@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Tricia Smith',
    title = 'Dr',
    role = 'Clinical Director',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'tsmith@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'tsmith@honeylakeclinic.com', 'Tricia Smith', 'Dr', 'Clinical Director', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'tsmith@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'James Johnson',
    title = 'Dr',
    role = 'Head of Pastoral Care Team',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'jjohnson@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'jjohnson@honeylakeclinic.com', 'James Johnson', 'Dr', 'Head of Pastoral Care Team', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'jjohnson@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Michelle Miller',
    title = NULL,
    role = 'Director of Nursing',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'mmiller@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'mmiller@honeylakeclinic.com', 'Michelle Miller', NULL, 'Director of Nursing', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'mmiller@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Albert "Mac" Legett',
    title = NULL,
    role = 'Tech Manager',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'alegett@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'alegett@honeylakeclinic.com', 'Albert "Mac" Legett', NULL, 'Tech Manager', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'alegett@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Annalisa Sookdeo',
    title = NULL,
    role = 'Director of Case Management',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'asookdeo@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'asookdeo@honeylakeclinic.com', 'Annalisa Sookdeo', NULL, 'Director of Case Management', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'asookdeo@honeylakeclinic.com'
);
UPDATE public.employees
SET full_name = 'Lloyd Burke',
    title = NULL,
    role = 'Head of Security',
    status = 'active'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND email = 'lburke@honeylakeclinic.com';
INSERT INTO public.employees (company_id, email, full_name, title, role, status)
SELECT '9ea3677d-be6c-46df-a41c-d22f01e88756', 'lburke@honeylakeclinic.com', 'Lloyd Burke', NULL, 'Head of Security', 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM public.employees e
  WHERE e.company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
    AND e.email = 'lburke@honeylakeclinic.com'
);
-- Update question prompt/department/owner mapping by question number.
UPDATE public.exit_survey_questions
SET text = 'I feel better now than when I was admitted',
    department = NULL,
    owner_name = 'Caitlyn Morgan',
    owner_email = 'cmorgan@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 1;
UPDATE public.exit_survey_questions
SET text = 'I would recommend Honey Lake to someone needing treatment',
    department = NULL,
    owner_name = 'Caitlyn Morgan',
    owner_email = 'cmorgan@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 2;
UPDATE public.exit_survey_questions
SET text = 'Before arriving, the Admissions Team helped me feel supported during the admissions process',
    department = 'Admissions',
    owner_name = 'Nikki George',
    owner_email = 'ngeorge@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 3;
UPDATE public.exit_survey_questions
SET text = 'I felt genuinely welcomed on the day that I arrived',
    department = 'Patient Experience',
    owner_name = 'Shaquel Payne',
    owner_email = 'spayne@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 4;
UPDATE public.exit_survey_questions
SET text = 'My schedule was explained to me in a way that I can understand',
    department = 'Patient Experience',
    owner_name = 'Shaquel Payne',
    owner_email = 'spayne@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 5;
UPDATE public.exit_survey_questions
SET text = 'Orientation clearly communicated expectations of the program',
    department = 'Patient Advocacy',
    owner_name = 'Heather Plain',
    owner_email = 'hplain@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 6;
UPDATE public.exit_survey_questions
SET text = 'I was satisfied with the enrichment services (spa, salon, equine, wellness, etc.)',
    department = 'Spa/Salon',
    owner_name = 'Dawn Rettig',
    owner_email = 'drettig@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 7;
UPDATE public.exit_survey_questions
SET text = 'I was satisfied with the psychiatrist I was assigned',
    department = 'Medical Director',
    owner_name = 'Karl Benzio',
    owner_email = 'kbenzio@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 8;
UPDATE public.exit_survey_questions
SET text = 'I felt informed by my psychiatric provider about my diagnosis and prescribed medications',
    department = 'Medical Director',
    owner_name = 'Karl Benzio',
    owner_email = 'kbenzio@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 9;
UPDATE public.exit_survey_questions
SET text = 'I felt my physical medical needs were addressed by my primary care provider',
    department = 'Medical Director',
    owner_name = 'Karl Benzio',
    owner_email = 'kbenzio@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 10;
UPDATE public.exit_survey_questions
SET text = 'I was satisfied with the primary therapist I was assigned',
    department = 'Clinical',
    owner_name = 'Tricia Smith',
    owner_email = 'tsmith@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 11;
UPDATE public.exit_survey_questions
SET text = 'I felt my therapist addressed my needs',
    department = 'Clinical',
    owner_name = 'Tricia Smith',
    owner_email = 'tsmith@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 12;
UPDATE public.exit_survey_questions
SET text = 'I was satisfied with the pastoral care I was assigned',
    department = 'Pastoral Care',
    owner_name = 'James Johnson',
    owner_email = 'jjohnson@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 13;
UPDATE public.exit_survey_questions
SET text = 'Nursing Staff treated me with courtesy and respect',
    department = 'Nursing',
    owner_name = 'Michelle Miller',
    owner_email = 'mmiller@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 14;
UPDATE public.exit_survey_questions
SET text = 'Tech Staff was empathetic to my needs',
    department = 'Tech Services',
    owner_name = 'Albert "Mac" Legett',
    owner_email = 'alegett@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 15;
UPDATE public.exit_survey_questions
SET text = 'I understand my discharge plan',
    department = 'Case Management',
    owner_name = 'Annalisa Sookdeo',
    owner_email = 'asookdeo@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 16;
UPDATE public.exit_survey_questions
SET text = 'I felt like I had input into my treatment goals',
    department = 'Clinical + Medical',
    owner_name = 'Tricia Smith',
    owner_email = 'tsmith@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 17;
UPDATE public.exit_survey_questions
SET text = 'I felt like my treatment was tailored to my specific needs',
    department = 'Clinical + Medical',
    owner_name = 'Tricia Smith',
    owner_email = 'tsmith@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 18;
UPDATE public.exit_survey_questions
SET text = 'The therapy groups were helpful to my healing and growth',
    department = 'Clinical',
    owner_name = 'Tricia Smith',
    owner_email = 'tsmith@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 19;
UPDATE public.exit_survey_questions
SET text = 'I felt like my experience at Honey Lake Clinic helped me grow in my relationship with God',
    department = 'Pastoral Care',
    owner_name = 'James Johnson',
    owner_email = 'jjohnson@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 20;
UPDATE public.exit_survey_questions
SET text = 'The food menu offers a good selection and variety',
    department = 'Culinary',
    owner_name = 'Dawn Rettig',
    owner_email = 'drettig@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 21;
UPDATE public.exit_survey_questions
SET text = 'I was able to navigate the facility with ease',
    department = 'Patient Experience',
    owner_name = 'Shaquel Payne',
    owner_email = 'spayne@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 22;
UPDATE public.exit_survey_questions
SET text = 'My accommodation was clean and comfortable',
    department = 'Patient Experience',
    owner_name = 'Shaquel Payne',
    owner_email = 'spayne@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 23;
UPDATE public.exit_survey_questions
SET text = 'I felt safe and secure on the facility',
    department = 'Security',
    owner_name = 'Lloyd Burke',
    owner_email = 'lburke@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 24;
UPDATE public.exit_survey_questions
SET text = 'I felt like I have the ability to report abuse at any time',
    department = 'Patient Advocacy',
    owner_name = 'Heather Plain',
    owner_email = 'hplain@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 25;
UPDATE public.exit_survey_questions
SET text = 'I was treated with dignity and respect by staff',
    department = 'Patient Advocacy',
    owner_name = 'Heather Plain',
    owner_email = 'hplain@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 26;
UPDATE public.exit_survey_questions
SET text = 'What could have improved your stay at Honey Lake Clinic?',
    department = NULL,
    owner_name = 'Caitlyn Morgan',
    owner_email = 'cmorgan@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 27;
UPDATE public.exit_survey_questions
SET text = 'What has positively impacted your stay at Honey Lake Clinic?',
    department = NULL,
    owner_name = 'Caitlyn Morgan',
    owner_email = 'cmorgan@honeylakeclinic.com'
WHERE company_id = '9ea3677d-be6c-46df-a41c-d22f01e88756'
  AND question_number = 28;
COMMIT;
