// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvunixucwpdcdtswnpmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2dW5peHVjd3BkY2R0c3ducG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNDkwNTUsImV4cCI6MjA4MzkyNTA1NX0.mW84YlakNh--nDv72dY_ExfPZEpy4fJsucdfv61kNrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});